#!/bin/bash
GVT_PCI="0000:00:02.0"
GVT_GUID="fdfd4e27-f44a-425f-b62d-e840a147b9cd"
MDEV_TYPE="i915-GVTg_V5_2"
DOMAIN="win10_pro_x64"
if [ $# -ge 3 ]; then
    if [ $1 = "$DOMAIN" -a $2 = "prepare" -a $3 = "begin" ]; then
        echo "$GVT_GUID" > "/sys/bus/pci/devices/$GVT_PCI/mdev_supported_types/$MDEV_TYPE/create"
    elif [ $1 = "$DOMAIN" -a $2 = "release" -a $3 = "end" ]; then
        echo 1 > /sys/bus/pci/devices/$GVT_PCI/$GVT_GUID/remove
    fi
fi